#!/bin/bash

# Apache and Shibd gets grumpy about PID files pre-existing from previous runs
rm -f /etc/httpd/run/httpd.pid /var/lock/subsys/shibd

# Copy custom shibboleth configuration into the configuration folder
if [ -d /opt/shibboleth-config ];then
    cp -r /opt/shibboleth-config/* /etc/shibboleth
fi

# Start Shibd
/etc/shibboleth/shibd-redhat start

# Copy custom http configuration into the configuration folder
if [ -d /opt/httpd-config ];then
    cp -r /opt/httpd-config/* /etc/httpd
fi

# Copy custom zenodo configuration into the configuration folder
if [ -d /opt/zenodo-config ];then
    cp -r /opt/zenodo-config/* /opt/zenodo
fi

# Copy custom invenio configuration into the configuration folder
if [ -d /opt/invenio-config ];then
    cp -r /opt/invenio-config/* /opt/zenodo_venv/var/instance
fi

# Start httpd
exec httpd -DFOREGROUND
